// Generated by CoffeeScript 1.9.2
(function() {
  var autoprefixer, compass, concat, csso, gulp, imagemin, paths, pngquant, uglify;

  gulp = require("gulp");

  compass = require("gulp-compass");

  autoprefixer = require("gulp-autoprefixer");

  csso = require("gulp-csso");

  concat = require("gulp-concat");

  uglify = require("gulp-uglify");

  imagemin = require('gulp-imagemin');

  pngquant = require('imagemin-pngquant');

  paths = {
    cssSource: "source/css"
  };

  gulp.task("css", function() {
    return gulp.src("src/css/**/*.scss").pipe(compass({
      config_file: "./config.rb",
      css: "src/css",
      sass: "src/css"
    })).pipe(autoprefixer({
      browsers: ["last 6 version", "> 1%", "ie 8"]
    })).pipe(csso()).pipe(gulp.dest("public/css"));
  });

  gulp.task("img", function() {
    return gulp.src("./src/image/**/*").pipe(imagemin({
      progressive: true,
      use: [pngquant()]
    })).pipe(gulp.dest('public/image'));
  });

  gulp.task("w", function() {
    gulp.watch("./src/css/**/*.scss", ["css"]);
    return gulp.watch("./src/img/**/*", ["img"]);
  });

  gulp.task("default", ["css", "img"]);

}).call(this);
